//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.05 at 11:04:38 AM GMT 
//


package Main;

import PhoneShop.PhoneShop;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.namespace.QName;
import PhoneShop.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Main package.
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final String localpart = "phoneShop";
    private final static QName _PhoneShop_QNAME = new QName("", localpart);

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Main
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PhoneShop }
     * 
     */
    public Library createLibrary() {
        return new Library();
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link Catalog }
     * 
     */
    public Catalog createCatalog() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link Lending }
     * 
     */
    public Lending createLending() {
        return new Lending();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    public Phone createPhone() { return new Phone(); }

    public PhoneLease createPhoneLease() { return new PhoneLease(); }

    public PhoneSale createPhoneSale() { return new PhoneSale(); }

    public Customer createCustomer() { return new Customer(); }

    public Salesman createSalesman() { return new Salesman(); }

    public PhoneShop createPhoneShop() { return new PhoneShop(); }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PhoneShop }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = localpart)
    public JAXBElement<PhoneShop> createMyPhoneShop(PhoneShop value) {
        return new JAXBElement<PhoneShop>(_PhoneShop_QNAME, PhoneShop.class, null, value);
    }

}
